backend:
  name: git-gateway
  branch: main 
site_url: https://mandragorastv.com
media_folder: "assets/uploads" # Carpeta donde se guardar치n los archivos subidos
public_folder: "/uploads"
collections:
  - name: 'posts'  # Nombre de la colecci칩n (ejemplo: posts)
    label: 'Posts'
    folder: 'src/content/posts'  # Carpeta donde estar치n los archivos Markdown
    create: true  # Permitir la creaci칩n de nuevos posts
    fields:
      - name: 'title'
        label: 'Title'
        widget: 'string'
      - name: 'date'
        label: 'Date'
        widget: 'datetime'
      - name: 'body'
        label: 'Body'
        widget: 'markdown'
locale: 'es'